name: "Stephen Brennan"
description: "A totally not boring blog."

url: "http://stephen-brennan.com"

paginate: 10
paginate_path: "blog/page:num"

markdown: kramdown
permalink: pretty
highlighter: pygments