name: "Stephen Brennan"
description: "C and Python programmer extraordinaire"
logo: "/images/me.jpg"

url: "http://stephen-brennan.com"

paginate: 5
paginate_path: "blog/page:num"

markdown: redcarpet
highlighter: pygments
permalink: pretty