name: Stephen Brennan
author: Stephen Brennan
title: Stephen Brennan's Blog
description: Stephen Brennan's personal website and blog.
keywords: blog programming student resume technology talks
tagline: C and Python programmer extraordinaire
logo: /images/me.jpg

url: http://stephen-brennan.com

gems: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page:num"

markdown: kramdown
highlighter: rouge
permalink: pretty

kramdown:
  input: GFM
  hard_wrap: false

exclude: ["CNAME", "README.md"]

disqus: stephenbrennan
analytics: UA-58675248-2