name: Stephen Brennan
author: Stephen Brennan
title: Stephen Brennan's Blog
description: Stephen Brennan's personal website and blog.
keywords: blog programming student resume technology talks
tagline: C and Python programmer extraordinaire
logo: /images/me.jpg

url: http://stephen-brennan.com

paginate: 5
paginate_path: "blog/page:num"

markdown: redcarpet
highlighter: pygments
permalink: pretty

exclude: ["CNAME", "README.md"]

disqus: stephenbrennan
analytics: UA-58675248-2